name: flutter_ankidroid
description: A flutter wrapper over the java AnkiDroid API.
version: 0.1.0
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  async: ^2.11.0
  flutter_isolate: ^2.0.4


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.aaalkoud.ankidroid
        pluginClass: AnkidroidPlugin
